import type { Product } from './types';

/**
 * The starting catalogue. Used directly until Supabase is connected, and
 * mirrored in `supabase/seed.sql` for loading into the database.
 *
 * Photos: drop a file named `<slug>.jpg` into `public/products/` and it is
 * picked up automatically — see `ProductImage`.
 */
export const seedProducts: Product[] = [
  {
    id: 'seed-1',
    created_at: '2026-01-01T00:00:00Z',
    name: 'Flower Seat Belt Pads (Set of 2)',
    slug: 'flower-seat-belt-pads',
    description:
      'Soft padded shoulder covers with beaded flower appliqués and a rhinestone centre. Velcro on, no fiddling — and no more seat belt digging into your shoulder.',
    category: 'car-accessories',
    price: 159,
    tiers: [
      { min_qty: 5, price: 145 },
      { min_qty: 10, price: 129 },
    ],
    personalised: true,
    personalisation_note: 'Tell us which flower colour you want',
    options: ['White daisy', 'Pink', 'Orange', 'Yellow'],
    bulk_from: 10,
    image_url: null,
    in_stock: true,
    featured: true,
  },
  {
    id: 'seed-2',
    created_at: '2026-01-02T00:00:00Z',
    name: 'Personalised Frosted Glass Tumbler',
    slug: 'personalised-frosted-glass-tumbler',
    description:
      'Frosted glass can with a bamboo lid and reusable straw, with the name of your choice in script. The bridesmaid gift everyone actually keeps.',
    category: 'drinkware',
    price: 189,
    tiers: [
      { min_qty: 4, price: 175 },
      { min_qty: 6, price: 165 },
      { min_qty: 10, price: 155 },
    ],
    personalised: true,
    personalisation_note:
      'Send the name for each tumbler, plus any title like “Bride” or “Maid of honour”',
    options: ['Blush pink', 'Clear frosted', 'White'],
    bulk_from: 6,
    image_url: null,
    in_stock: true,
    featured: true,
  },
  {
    id: 'seed-3',
    created_at: '2026-01-03T00:00:00Z',
    name: 'Personalised Acrylic Photo Calendar',
    slug: 'personalised-acrylic-photo-calendar',
    description:
      'Clear acrylic keepsake on a stand, printed with your photo, the month and year, and the special day circled in a heart. Add a Spotify code and the song plays when they scan it.',
    category: 'personalised',
    price: 399,
    tiers: [{ min_qty: 3, price: 369 }],
    personalised: true,
    personalisation_note:
      'Send the photo, the name, the date to circle, and the song if you want a Spotify code',
    options: [],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: true,
  },
  {
    id: 'seed-4',
    created_at: '2026-01-04T00:00:00Z',
    name: 'Personalised Silicone Baby Feeding Set',
    slug: 'personalised-silicone-baby-feeding-set',
    description:
      'Seven pieces in food-grade silicone — suction bowl, divided plate, bib, cup, spoon, fork and scoop — engraved with your little one’s name. Dishwasher safe and soft on new gums.',
    category: 'baby',
    price: 649,
    tiers: [{ min_qty: 3, price: 599 }],
    personalised: true,
    personalisation_note: 'Tell us the baby’s name and the colour you’d like',
    options: ['Dusty rose', 'Sage', 'Beige', 'Grey'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: true,
  },
  {
    id: 'seed-5',
    created_at: '2026-01-05T00:00:00Z',
    name: '“Just a Girl” Car Decal',
    slug: 'just-a-girl-car-decal',
    description:
      '“Please be patient, I’m just a girl.” in a retro script with a coquette bow underneath. Weatherproof vinyl that peels off cleanly when you’re over it.',
    category: 'decals',
    price: 89,
    tiers: [
      { min_qty: 5, price: 79 },
      { min_qty: 10, price: 69 },
    ],
    personalised: true,
    personalisation_note: 'Pick your colour',
    options: ['Bubblegum pink', 'Baby blue', 'White'],
    bulk_from: 10,
    image_url: null,
    in_stock: true,
    featured: true,
  },
  {
    id: 'seed-6',
    created_at: '2026-01-06T00:00:00Z',
    name: 'Princess on Board Decal',
    slug: 'princess-on-board-decal',
    description:
      'Blowing-a-kiss silhouette in soft pink for the back window. Cut vinyl, no background — it looks painted on.',
    category: 'decals',
    price: 79,
    tiers: [{ min_qty: 5, price: 69 }],
    personalised: true,
    personalisation_note: 'Pick your colour',
    options: ['Pink', 'White', 'Black'],
    bulk_from: 10,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-7',
    created_at: '2026-01-07T00:00:00Z',
    name: 'Cartoon Fuel Cap Decal',
    slug: 'cartoon-fuel-cap-decal',
    description:
      'Cheeky little mouse holding the pump, sized for a fuel flap. Makes the petrol price sting slightly less.',
    category: 'decals',
    price: 79,
    tiers: [{ min_qty: 5, price: 69 }],
    personalised: true,
    personalisation_note: 'Tell us your fuel type for the nozzle — 93, 95 or diesel',
    options: ['95 unleaded', '93 unleaded', 'Diesel'],
    bulk_from: 10,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-8',
    created_at: '2026-01-08T00:00:00Z',
    name: 'Cheeky Cup Holder Coasters (Set of 2)',
    slug: 'cheeky-cup-holder-coasters',
    description:
      'Pink silicone coasters for your cup holders, with the viral “Don’t mess up the car — please” print. Catches every spill and every passenger’s attention.',
    category: 'car-accessories',
    price: 129,
    tiers: [{ min_qty: 5, price: 115 }],
    personalised: false,
    personalisation_note: null,
    options: ['Pink', 'Black'],
    bulk_from: 10,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-9',
    created_at: '2026-01-09T00:00:00Z',
    name: 'Flower Air Vent Clips (Set of 4)',
    slug: 'flower-air-vent-clips',
    description:
      'Enamel daisies with gold centres that clip onto your air vents in two sizes. Add a drop of your own oil and they double as a diffuser.',
    category: 'car-accessories',
    price: 119,
    tiers: [{ min_qty: 5, price: 105 }],
    personalised: true,
    personalisation_note: 'Pick your colour',
    options: ['Pink', 'White', 'Yellow'],
    bulk_from: 10,
    image_url: null,
    in_stock: true,
    featured: true,
  },
  {
    id: 'seed-10',
    created_at: '2026-01-10T00:00:00Z',
    name: 'Floral Steering Wheel Cover',
    slug: 'floral-steering-wheel-cover',
    description:
      'Stretch-fit cover in black with pink blossoms scattered around it. Grippy in traffic, and it hides a sun-faded wheel.',
    category: 'car-accessories',
    price: 199,
    tiers: [{ min_qty: 5, price: 179 }],
    personalised: false,
    personalisation_note: null,
    options: ['Pink flowers', 'White flowers'],
    bulk_from: 10,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-11',
    created_at: '2026-01-11T00:00:00Z',
    name: '360° Car Headrest Hooks (Set of 2)',
    slug: 'car-headrest-hooks',
    description:
      'Rotating hooks that clip behind the headrest and swing a full circle, so handbags and shopping stop tipping over on the corners.',
    category: 'car-accessories',
    price: 89,
    tiers: [{ min_qty: 5, price: 79 }],
    personalised: true,
    personalisation_note: 'Pick your colour',
    options: ['Black', 'White', 'Beige'],
    bulk_from: 10,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-12',
    created_at: '2026-01-12T00:00:00Z',
    name: 'Personalised Framed Calendar Print',
    slug: 'personalised-framed-calendar-print',
    description:
      'Framed print pairing a favourite photo with the month it happened, a quote of your choosing and the date circled. A birthday or anniversary gift that goes straight on the wall.',
    category: 'personalised',
    price: 449,
    tiers: [{ min_qty: 3, price: 419 }],
    personalised: true,
    personalisation_note:
      'Send the photo, the full name, the date, and the quote you want on it',
    options: ['White frame', 'Black frame', 'Oak frame'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-13',
    created_at: '2026-01-13T00:00:00Z',
    name: 'Line Art Framed Print',
    slug: 'line-art-framed-print',
    description:
      'Single-line drawing of a woman in a towel turban, framed in light oak. Quiet, modern and it suits any bedroom or bathroom.',
    category: 'wall-art',
    price: 399,
    tiers: [{ min_qty: 3, price: 369 }],
    personalised: true,
    personalisation_note: 'Pick your frame and size',
    options: ['A4', 'A3', 'Oak frame', 'Black frame'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-14',
    created_at: '2026-01-14T00:00:00Z',
    name: '“God Made a Way” Print',
    slug: 'god-made-a-way-print',
    description:
      '“Long story short, God made a way.” Set in an elegant serif with a soft metallic finish that catches the light.',
    category: 'wall-art',
    price: 349,
    tiers: [{ min_qty: 3, price: 319 }],
    personalised: true,
    personalisation_note: 'Pick your size and finish',
    options: ['A4', 'A3', 'Champagne', 'Matte black'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-15',
    created_at: '2026-01-15T00:00:00Z',
    name: 'Dino Hooded Onesie',
    slug: 'dino-hooded-onesie',
    description:
      'Plush fleece romper in bright green with a spiked tail and a hooded dinosaur face. Zips right up, keeps a toddler warm indoors, and gets worn far past pyjama time.',
    category: 'baby',
    price: 299,
    tiers: [{ min_qty: 3, price: 279 }],
    personalised: false,
    personalisation_note: null,
    options: ['6-12 months', '12-18 months', '18-24 months', '2-3 years'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
];
