import type { Product } from './types';

/**
 * The starting catalogue. Used directly until Supabase is connected, and
 * mirrored in `supabase/seed.sql` for loading into the database.
 *
 * Photos: drop a file named `<slug>.jpg` into `public/products/` and it is
 * picked up automatically — see `ProductImage`.
 */
export const seedProducts: Product[] = [
  {
    id: 'seed-1',
    created_at: '2026-01-01T00:00:00Z',
    name: 'Flower Seat Belt Pads (Set of 2)',
    slug: 'flower-seat-belt-pads',
    description:
      'Soft padded shoulder covers with beaded flower appliqués and a rhinestone centre. Velcro on, no fiddling — and no more seat belt digging into your shoulder.',
    category: 'car-accessories',
    price: 159,
    tiers: [
      { min_qty: 5, price: 145 },
      { min_qty: 10, price: 129 },
    ],
    personalised: true,
    personalisation_note: 'Tell us which flower colour you want',
    options: ['White daisy', 'Pink', 'Orange', 'Yellow'],
    bulk_from: 10,
    image_url: null,
    in_stock: true,
    featured: true,
  },
  {
    id: 'seed-2',
    created_at: '2026-01-02T00:00:00Z',
    name: 'Personalised Frosted Glass Tumbler',
    slug: 'personalised-frosted-glass-tumbler',
    description:
      'Frosted glass can with a bamboo lid and reusable straw, with the name of your choice in script. The bridesmaid gift everyone actually keeps.',
    category: 'drinkware',
    price: 189,
    tiers: [
      { min_qty: 4, price: 175 },
      { min_qty: 6, price: 165 },
      { min_qty: 10, price: 155 },
    ],
    personalised: true,
    personalisation_note:
      'Send the name for each tumbler, plus any title like “Bride” or “Maid of honour”',
    options: ['Blush pink', 'Clear frosted', 'White'],
    bulk_from: 6,
    image_url: null,
    in_stock: true,
    featured: true,
  },
  {
    id: 'seed-3',
    created_at: '2026-01-03T00:00:00Z',
    name: 'Personalised Acrylic Photo Calendar',
    slug: 'personalised-acrylic-photo-calendar',
    description:
      'Clear acrylic keepsake on a stand, printed with your photo, the month and year, and the special day circled in a heart. Add a Spotify code and the song plays when they scan it.',
    category: 'personalised',
    price: 399,
    tiers: [{ min_qty: 3, price: 369 }],
    personalised: true,
    personalisation_note:
      'Send the photo, the name, the date to circle, and the song if you want a Spotify code',
    options: [],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: true,
  },
  {
    id: 'seed-4',
    created_at: '2026-01-04T00:00:00Z',
    name: 'Personalised Silicone Baby Feeding Set',
    slug: 'personalised-silicone-baby-feeding-set',
    description:
      'Seven pieces in food-grade silicone — suction bowl, divided plate, bib, cup, spoon, fork and scoop — engraved with your little one’s name. Dishwasher safe and soft on new gums.',
    category: 'baby',
    price: 649,
    tiers: [{ min_qty: 3, price: 599 }],
    personalised: true,
    personalisation_note: 'Tell us the baby’s name and the colour you’d like',
    options: ['Dusty rose', 'Sage', 'Beige', 'Grey'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: true,
  },
  {
    id: 'seed-5',
    created_at: '2026-01-05T00:00:00Z',
    name: '“Just a Girl” Car Decal',
    slug: 'just-a-girl-car-decal',
    description:
      '“Please be patient, I’m just a girl.” in a retro script with a coquette bow underneath. Weatherproof vinyl that peels off cleanly when you’re over it.',
    category: 'decals',
    price: 89,
    tiers: [
      { min_qty: 5, price: 79 },
      { min_qty: 10, price: 69 },
    ],
    personalised: true,
    personalisation_note: 'Pick your colour',
    options: ['Bubblegum pink', 'Baby blue', 'White'],
    bulk_from: 10,
    image_url: null,
    in_stock: true,
    featured: true,
  },
  {
    id: 'seed-6',
    created_at: '2026-01-06T00:00:00Z',
    name: 'Princess on Board Decal',
    slug: 'princess-on-board-decal',
    description:
      'Blowing-a-kiss silhouette in soft pink for the back window. Cut vinyl, no background — it looks painted on.',
    category: 'decals',
    price: 79,
    tiers: [{ min_qty: 5, price: 69 }],
    personalised: true,
    personalisation_note: 'Pick your colour',
    options: ['Pink', 'White', 'Black'],
    bulk_from: 10,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-7',
    created_at: '2026-01-07T00:00:00Z',
    name: 'Cartoon Fuel Cap Decal',
    slug: 'cartoon-fuel-cap-decal',
    description:
      'Cheeky little mouse holding the pump, sized for a fuel flap. Makes the petrol price sting slightly less.',
    category: 'decals',
    price: 79,
    tiers: [{ min_qty: 5, price: 69 }],
    personalised: true,
    personalisation_note: 'Tell us your fuel type for the nozzle — 93, 95 or diesel',
    options: ['95 unleaded', '93 unleaded', 'Diesel'],
    bulk_from: 10,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-8',
    created_at: '2026-01-08T00:00:00Z',
    name: 'Cheeky Cup Holder Coasters (Set of 2)',
    slug: 'cheeky-cup-holder-coasters',
    description:
      'Pink silicone coasters for your cup holders, with the viral “Don’t mess up the car — please” print. Catches every spill and every passenger’s attention.',
    category: 'car-accessories',
    price: 129,
    tiers: [{ min_qty: 5, price: 115 }],
    personalised: false,
    personalisation_note: null,
    options: ['Pink', 'Black'],
    bulk_from: 10,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-9',
    created_at: '2026-01-09T00:00:00Z',
    name: 'Flower Air Vent Clips (Set of 4)',
    slug: 'flower-air-vent-clips',
    description:
      'Enamel daisies with gold centres that clip onto your air vents in two sizes. Add a drop of your own oil and they double as a diffuser.',
    category: 'car-accessories',
    price: 119,
    tiers: [{ min_qty: 5, price: 105 }],
    personalised: true,
    personalisation_note: 'Pick your colour',
    options: ['Pink', 'White', 'Yellow'],
    bulk_from: 10,
    image_url: null,
    in_stock: true,
    featured: true,
  },
  {
    id: 'seed-10',
    created_at: '2026-01-10T00:00:00Z',
    name: 'Floral Steering Wheel Cover',
    slug: 'floral-steering-wheel-cover',
    description:
      'Stretch-fit cover in black with pink blossoms scattered around it. Grippy in traffic, and it hides a sun-faded wheel.',
    category: 'car-accessories',
    price: 199,
    tiers: [{ min_qty: 5, price: 179 }],
    personalised: false,
    personalisation_note: null,
    options: ['Pink flowers', 'White flowers'],
    bulk_from: 10,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-11',
    created_at: '2026-01-11T00:00:00Z',
    name: '360° Car Headrest Hooks (Set of 2)',
    slug: 'car-headrest-hooks',
    description:
      'Rotating hooks that clip behind the headrest and swing a full circle, so handbags and shopping stop tipping over on the corners.',
    category: 'car-accessories',
    price: 89,
    tiers: [{ min_qty: 5, price: 79 }],
    personalised: true,
    personalisation_note: 'Pick your colour',
    options: ['Black', 'White', 'Beige'],
    bulk_from: 10,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-12',
    created_at: '2026-01-12T00:00:00Z',
    name: 'Personalised Framed Calendar Print',
    slug: 'personalised-framed-calendar-print',
    description:
      'Framed print pairing a favourite photo with the month it happened, a quote of your choosing and the date circled. A birthday or anniversary gift that goes straight on the wall.',
    category: 'personalised',
    price: 449,
    tiers: [{ min_qty: 3, price: 419 }],
    personalised: true,
    personalisation_note:
      'Send the photo, the full name, the date, and the quote you want on it',
    options: ['White frame', 'Black frame', 'Oak frame'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-13',
    created_at: '2026-01-13T00:00:00Z',
    name: 'Line Art Framed Print',
    slug: 'line-art-framed-print',
    description:
      'Single-line drawing of a woman in a towel turban, framed in light oak. Quiet, modern and it suits any bedroom or bathroom.',
    category: 'wall-art',
    price: 399,
    tiers: [{ min_qty: 3, price: 369 }],
    personalised: true,
    personalisation_note: 'Pick your frame and size',
    options: ['A4', 'A3', 'Oak frame', 'Black frame'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-14',
    created_at: '2026-01-14T00:00:00Z',
    name: '“God Made a Way” Print',
    slug: 'god-made-a-way-print',
    description:
      '“Long story short, God made a way.” Set in an elegant serif with a soft metallic finish that catches the light.',
    category: 'wall-art',
    price: 349,
    tiers: [{ min_qty: 3, price: 319 }],
    personalised: true,
    personalisation_note: 'Pick your size and finish',
    options: ['A4', 'A3', 'Champagne', 'Matte black'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-15',
    created_at: '2026-01-15T00:00:00Z',
    name: 'Dino Hooded Onesie',
    slug: 'dino-hooded-onesie',
    description:
      'Plush fleece romper in bright green with a spiked tail and a hooded dinosaur face. Zips right up, keeps a toddler warm indoors, and gets worn far past pyjama time.',
    category: 'baby',
    price: 299,
    tiers: [{ min_qty: 3, price: 279 }],
    personalised: false,
    personalisation_note: null,
    options: ['6-12 months', '12-18 months', '18-24 months', '2-3 years'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-16',
    created_at: '2026-01-16T00:00:00Z',
    name: 'Personalised Photo Phone Case',
    slug: 'personalised-photo-phone-case',
    description:
      'Your photo printed edge to edge on a shockproof case, with a matching flower wrist strap so it never slips out of your hand.',
    category: 'phone-cases',
    price: 249,
    tiers: [{ min_qty: 3, price: 229 }],
    personalised: true,
    personalisation_note: 'Send the photo and your exact phone model',
    options: ['Orange', 'Blush pink', 'Cream', 'Sage'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-17',
    created_at: '2026-01-17T00:00:00Z',
    name: '“Dad & Me” Baby Tee',
    slug: 'dad-and-me-baby-tee',
    description:
      'Soft cotton tee scattered with pink hearts and a little fist bump between father and child. The photo everyone takes on Father’s Day.',
    category: 'baby',
    price: 189,
    tiers: [{ min_qty: 3, price: 175 }],
    personalised: true,
    personalisation_note: 'Tell us the size you need',
    options: ['0-6 months', '6-12 months', '12-18 months', '18-24 months', '2-3 years'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-18',
    created_at: '2026-01-18T00:00:00Z',
    name: 'Custom Photo Canvas',
    slug: 'custom-photo-canvas',
    description:
      'Your favourite family photo stretched over a wooden frame, ready to hang straight out of the box. Colours come out warm, not washed out.',
    category: 'wall-art',
    price: 599,
    tiers: [{ min_qty: 2, price: 549 }],
    personalised: true,
    personalisation_note: 'Send the photo and pick your size',
    options: ['20x30cm', '30x40cm', '40x60cm', '50x70cm'],
    bulk_from: 3,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-19',
    created_at: '2026-01-19T00:00:00Z',
    name: 'Wedding Photo Phone Case',
    slug: 'wedding-photo-phone-case',
    description:
      'A glossy case printed with your own photo and a soft black bumper. Made for the couple who want the day on them all the time.',
    category: 'phone-cases',
    price: 229,
    tiers: [{ min_qty: 3, price: 209 }],
    personalised: true,
    personalisation_note: 'Send the photo and your exact phone model',
    options: ['Glossy', 'Matte'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-20',
    created_at: '2026-01-20T00:00:00Z',
    name: 'Personalised Dad Keyring',
    slug: 'personalised-dad-keyring',
    description:
      'Brushed steel dog tag engraved with a fist bump, hung with a little charm per child, each one engraved with their name.',
    category: 'personalised',
    price: 199,
    tiers: [{ min_qty: 3, price: 179 }],
    personalised: true,
    personalisation_note: 'Send each child’s name, and tell us boy or girl for each charm',
    options: ['Black tag', 'Silver tag'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-21',
    created_at: '2026-01-21T00:00:00Z',
    name: '“The Day It All Began” Framed Print',
    slug: 'day-it-all-began-framed-print',
    description:
      'Your photo cut into a heart above the month it happened, with the date circled and both names down the side. An anniversary gift that lands.',
    category: 'wall-art',
    price: 449,
    tiers: [{ min_qty: 3, price: 419 }],
    personalised: true,
    personalisation_note: 'Send the photo, both names, and the date to circle',
    options: ['A4', 'A3', 'Black frame', 'Oak frame'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-22',
    created_at: '2026-01-22T00:00:00Z',
    name: '“Super Mom” Phone Case',
    slug: 'super-mom-phone-case',
    description:
      'Matte black case with a mom-and-kids illustration in soft blue. No personalising needed, it just says it.',
    category: 'phone-cases',
    price: 199,
    tiers: [{ min_qty: 3, price: 179 }],
    personalised: true,
    personalisation_note: 'Tell us your exact phone model',
    options: ['One child', 'Two children', 'Three children'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-23',
    created_at: '2026-01-23T00:00:00Z',
    name: 'Spotify Photo Collage Print',
    slug: 'spotify-photo-collage-print',
    description:
      'Four of your photos around a scannable song code, so the track plays when anyone points a phone at it. Printed on thick matte paper.',
    category: 'wall-art',
    price: 349,
    tiers: [{ min_qty: 3, price: 319 }],
    personalised: true,
    personalisation_note: 'Send four photos and the song you want the code for',
    options: ['20x30cm', '30x40cm', '40x60cm', '50x70cm'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-24',
    created_at: '2026-01-24T00:00:00Z',
    name: 'Personalised Moon Crystal Lamp',
    slug: 'personalised-moon-crystal-lamp',
    description:
      'A moon etched inside a glass sphere with your names and date, lit warm from a wooden base. Looks like a paperweight until you switch it on.',
    category: 'personalised',
    price: 449,
    tiers: [{ min_qty: 3, price: 419 }],
    personalised: true,
    personalisation_note: 'Send both names and the date to engrave',
    options: ['Warm white light', 'Colour changing'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-25',
    created_at: '2026-01-25T00:00:00Z',
    name: 'Personalised Birthday Newspaper',
    slug: 'personalised-birthday-newspaper',
    description:
      'A full front page made up about them, with your photos and their name in the headline. Guests read the whole thing at the party.',
    category: 'personalised',
    price: 299,
    tiers: [{ min_qty: 3, price: 279 }],
    personalised: true,
    personalisation_note: 'Send the photos, the name, the age and anything you want written in',
    options: ['A3', 'A2'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-26',
    created_at: '2026-01-26T00:00:00Z',
    name: 'Personalised Photo Glass Block',
    slug: 'personalised-photo-glass-block',
    description:
      'A thick square of glass with your photo printed inside it and your names underneath. Catches the light on a shelf all day.',
    category: 'personalised',
    price: 399,
    tiers: [{ min_qty: 3, price: 369 }],
    personalised: true,
    personalisation_note: 'Send the photo and the names to print',
    options: ['10x10cm', '15x15cm'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-27',
    created_at: '2026-01-27T00:00:00Z',
    name: 'Personalised Photo Crystal Lamp',
    slug: 'personalised-photo-crystal-lamp',
    description:
      'Your photo etched into a glass ball inside a heart, names and date underneath, sitting on a warm wooden light base.',
    category: 'personalised',
    price: 429,
    tiers: [{ min_qty: 3, price: 399 }],
    personalised: true,
    personalisation_note: 'Send the photo, both names and the date',
    options: ['Warm white light', 'Colour changing'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-28',
    created_at: '2026-01-28T00:00:00Z',
    name: 'Personalised Song Plaque Print',
    slug: 'personalised-song-plaque-print',
    description:
      'One photo above a song title and a player bar, framed simply. The song you both claim as yours, on the wall.',
    category: 'wall-art',
    price: 329,
    tiers: [{ min_qty: 3, price: 299 }],
    personalised: true,
    personalisation_note: 'Send the photo, the song name and the artist',
    options: ['A4', 'A3', 'Oak frame', 'Black frame'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-29',
    created_at: '2026-01-29T00:00:00Z',
    name: 'Personalised Satin Bride Robe',
    slug: 'personalised-satin-bride-robe',
    description:
      'Soft satin robe with the name and title in gold script across the back. What the whole bridal party gets ready in.',
    category: 'personalised',
    price: 449,
    tiers: [{ min_qty: 4, price: 419 }, { min_qty: 6, price: 399 }],
    personalised: true,
    personalisation_note: 'Send the name, title and date for each robe',
    options: ['White', 'Blush pink', 'Champagne', 'Black'],
    bulk_from: 4,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-30',
    created_at: '2026-01-30T00:00:00Z',
    name: '“Love” Definition Photo Print',
    slug: 'love-definition-photo-print',
    description:
      'Four of your photos above the word love written out like a dictionary entry, with both names in the definition.',
    category: 'wall-art',
    price: 399,
    tiers: [{ min_qty: 3, price: 369 }],
    personalised: true,
    personalisation_note: 'Send four photos and both names',
    options: ['A4', 'A3', 'Black frame', 'Oak frame'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-31',
    created_at: '2026-01-31T00:00:00Z',
    name: '“Boyfriend” Gift Bag',
    slug: 'boyfriend-gift-bag',
    description:
      'Heavy white bag with a black satin bow and script lettering. Turns whatever you bought into a proper gift.',
    category: 'personalised',
    price: 89,
    tiers: [{ min_qty: 5, price: 79 }],
    personalised: false,
    personalisation_note: null,
    options: ['Small', 'Medium', 'Large'],
    bulk_from: 10,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-32',
    created_at: '2026-02-01T00:00:00Z',
    name: 'Trifold Baby Photo Frame',
    slug: 'trifold-baby-photo-frame',
    description:
      'Three little frames hinged together in white wood, so the newborn photos stand up on their own on a shelf.',
    category: 'baby',
    price: 349,
    tiers: [{ min_qty: 3, price: 319 }],
    personalised: true,
    personalisation_note: 'Tell us the wording you want on each frame',
    options: ['White', 'Natural wood'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-33',
    created_at: '2026-02-02T00:00:00Z',
    name: '“Happy Birthday” Gift Bag',
    slug: 'happy-birthday-gift-bag',
    description:
      'The same heavy white bag with a black satin bow, lettered for a birthday. Buy a few, they get used all year.',
    category: 'personalised',
    price: 89,
    tiers: [{ min_qty: 5, price: 79 }],
    personalised: false,
    personalisation_note: null,
    options: ['Small', 'Medium', 'Large'],
    bulk_from: 10,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-34',
    created_at: '2026-02-03T00:00:00Z',
    name: '“To My Mom” Acrylic Plaque',
    slug: 'to-my-mom-acrylic-plaque',
    description:
      'A pink acrylic stand cut to shape, printed with a long letter to your mom. The one people actually read all the way through.',
    category: 'personalised',
    price: 299,
    tiers: [{ min_qty: 3, price: 279 }],
    personalised: true,
    personalisation_note: 'Tell us who it is from, and any wording you want changed',
    options: ['Pink', 'Clear', 'White'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-35',
    created_at: '2026-02-04T00:00:00Z',
    name: 'Personalised Face Photo Blanket',
    slug: 'personalised-face-photo-blanket',
    description:
      'Fleece blanket printed with a cut-out face and name repeated across it. Ridiculous in the best way, and genuinely warm.',
    category: 'baby',
    price: 649,
    tiers: [{ min_qty: 2, price: 599 }],
    personalised: true,
    personalisation_note: 'Send a clear face photo per person, plus the names',
    options: ['Pink', 'Blue', 'Grey', 'Cream'],
    bulk_from: 3,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-36',
    created_at: '2026-02-05T00:00:00Z',
    name: 'Personalised Bridal Slippers',
    slug: 'personalised-bridal-slippers',
    description:
      'Fluffy cross-strap slippers with the name in gold across the toe. Bridesmaids put them on and do not take them off.',
    category: 'personalised',
    price: 349,
    tiers: [{ min_qty: 4, price: 329 }, { min_qty: 6, price: 309 }],
    personalised: true,
    personalisation_note: 'Send the name and shoe size for each pair',
    options: ['White', 'Blush pink', 'Grey'],
    bulk_from: 4,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-37',
    created_at: '2026-02-06T00:00:00Z',
    name: 'Personalised Baby Birth Stats Light',
    slug: 'baby-birth-stats-light',
    description:
      'Acrylic panel engraved with the birth date, time, weight and length beside three photos, lit warm from a wooden base.',
    category: 'baby',
    price: 449,
    tiers: [{ min_qty: 3, price: 419 }],
    personalised: true,
    personalisation_note: 'Send the photos plus the full name, date, time, weight and length',
    options: ['Warm white light', 'Colour changing'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-38',
    created_at: '2026-02-07T00:00:00Z',
    name: '“To My Man” Acrylic Heart',
    slug: 'to-my-man-acrylic-heart',
    description:
      'A clear acrylic heart, printed with a letter to him and standing on its own. Small enough for a bedside table.',
    category: 'personalised',
    price: 299,
    tiers: [{ min_qty: 3, price: 279 }],
    personalised: true,
    personalisation_note: 'Tell us any wording you want changed, and who it is from',
    options: ['Clear', 'Frosted'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-39',
    created_at: '2026-02-08T00:00:00Z',
    name: 'Monogram Leather Phone Case',
    slug: 'monogram-leather-phone-case',
    description:
      'Soft leather-look case embossed with your initial in a floral letter, with a name and year underneath.',
    category: 'phone-cases',
    price: 249,
    tiers: [{ min_qty: 3, price: 229 }],
    personalised: true,
    personalisation_note: 'Send your initial, the name, the year and your exact phone model',
    options: ['Brown', 'Black', 'Tan'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-40',
    created_at: '2026-02-09T00:00:00Z',
    name: 'Personalised Family Mugs (Set of 2)',
    slug: 'personalised-family-mugs',
    description:
      'A pair of mugs printed with little cartoon versions of the kids and their names. The set that gets used every single morning.',
    category: 'drinkware',
    price: 299,
    tiers: [{ min_qty: 3, price: 279 }],
    personalised: true,
    personalisation_note: 'Send each child’s name, and tell us boy or girl for each character',
    options: ['Mum & Dad', 'Gogo & Mkhulu', 'Custom wording'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-41',
    created_at: '2026-02-10T00:00:00Z',
    name: 'Pink Dino Hooded Onesie',
    slug: 'pink-dino-hooded-onesie',
    description:
      'Bright pink fleece romper with a yellow tummy patch, a spiked tail and a dinosaur face on the hood. Zips down the front so nappy changes stay quick.',
    category: 'baby',
    price: 329,
    tiers: [{ min_qty: 2, price: 309 }],
    personalised: false,
    personalisation_note: null,
    options: ['0-6 months', '6-12 months', '12-18 months', '18-24 months'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-42',
    created_at: '2026-02-11T00:00:00Z',
    name: 'Green Dino Onesie with Mittens',
    slug: 'green-dino-hooded-onesie',
    description:
      'Olive fleece dino romper with a white tummy and a toothy hood, and it comes with matching mittens for the cold mornings.',
    category: 'baby',
    price: 349,
    tiers: [{ min_qty: 2, price: 329 }],
    personalised: false,
    personalisation_note: null,
    options: ['0-6 months', '6-12 months', '12-18 months', '18-24 months'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-43',
    created_at: '2026-02-12T00:00:00Z',
    name: 'Teddy Bear Hooded Onesie',
    slug: 'teddy-bear-hooded-onesie',
    description:
      'Chocolate brown teddy suit in thick fleece, with ears on the hood, a little tail at the back and covered feet. Buttons all the way down.',
    category: 'baby',
    price: 379,
    tiers: [{ min_qty: 2, price: 355 }],
    personalised: false,
    personalisation_note: null,
    options: ['0-6 months', '6-12 months', '12-18 months', '18-24 months'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-44',
    created_at: '2026-02-13T00:00:00Z',
    name: 'Panda Hooded Onesie',
    slug: 'panda-hooded-onesie',
    description:
      'Soft black and white panda romper with the face on the hood. The one that gets photographed the most.',
    category: 'baby',
    price: 349,
    tiers: [{ min_qty: 2, price: 329 }],
    personalised: false,
    personalisation_note: null,
    options: ['0-6 months', '6-12 months', '12-18 months', '18-24 months'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-45',
    created_at: '2026-02-14T00:00:00Z',
    name: 'Dino Romper & Hat Set',
    slug: 'dino-romper-and-hat-set',
    description:
      'Two pieces in 100 percent cotton muslin — a sleeveless romper with a spiked back and a matching dino hat. Made for summer, not for winter.',
    category: 'baby',
    price: 249,
    tiers: [{ min_qty: 3, price: 229 }],
    personalised: false,
    personalisation_note: null,
    options: ['0-3 months', '3-6 months', '6-9 months'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
  {
    id: 'seed-46',
    created_at: '2026-02-15T00:00:00Z',
    name: 'Red Dragon Hooded Onesie',
    slug: 'red-dragon-hooded-onesie',
    description:
      'Red fleece romper with yellow spikes down the back and little horns on the hood. Warm enough to be the whole outfit indoors.',
    category: 'baby',
    price: 329,
    tiers: [{ min_qty: 2, price: 309 }],
    personalised: false,
    personalisation_note: null,
    options: ['0-6 months', '6-12 months', '12-18 months', '18-24 months'],
    bulk_from: 5,
    image_url: null,
    in_stock: true,
    featured: false,
  },
];
